Added support for blank placeholder spaces.
matt8707/ha-fusion pull request #316
Opened 2024-01-30 04:06 UTC by xrolfex

This PR adds support for a new object type of placeholder. It offers a way to put in blank spaces to allow for custom layouts.

This is one way to address #313. It still needs localization and is a first attempt. Im not sure if this is how you would like to handle it.

<img width="1248" alt="image" src="https://github.com/matt8707/ha-fusion/assets/1327947/9327437d-d9ea-42e6-95ab-186029304a26">

<img width="542" alt="image" src="https://github.com/matt8707/ha-fusion/assets/1327947/7dc8c73e-de5f-4bd7-b5db-4e9489c19d5c">

<img width="1184" alt="image" src="https://github.com/matt8707/ha-fusion/assets/1327947/8ff1620d-5544-4ee8-93d5-a45b4e0bbdb7">

<img width="1147" alt="image" src="https://github.com/matt8707/ha-fusion/assets/1327947/3417529f-4758-4fd6-81cc-ec15d8b8d626">

2024-01-30 19:03 UTC, matt8707 commented
Looks good. It's somewhat related to sidebar > divider > empty option. So, it would be nice to maintain consistency in appearance. However, this could lead to confusion with "new object". So maybe that style but gray in color, what do you think?

![divider](https://github.com/matt8707/ha-fusion/assets/36163594/88eb932e-3cb4-46ff-930d-7955445117e8)

2024-01-31 00:32 UTC, xrolfex commented
So something more like this? Are you also thinking remove the placeholder text as well?

<img width="1146" alt="image" src="https://github.com/matt8707/ha-fusion/assets/1327947/69faf95d-7599-4289-9f34-ac6af88beab4">

2024-01-31 21:41 UTC, matt8707 commented
Yeah I'm thinking,
* Make it transparent white to differentiate from the yellow
* Use $lang('empty') instead of 'placeholder' (unsure if needed)
* Internally, rename it to 'empty'

2024-02-01 01:05 UTC, xrolfex commented
> Yeah I'm thinking,
> 
> * Make it transparent white to differentiate from the yellow
> * Use $lang('empty') instead of 'placeholder' (unsure if needed)
> * Internally, rename it to 'empty'

Got these taken card of; did remove the text during editing:

 
<img width="1135" alt="image" src="https://github.com/matt8707/ha-fusion/assets/1327947/dde2f150-74f1-4d3e-b9f2-52a2d7ae312d">

2024-02-01 04:53 UTC, matt8707 requested changes

2024-02-01 04:53 UTC, matt8707 commented on src/lib/Main/Empty.svelte
> +</style>
```suggestion
<script lang="ts">
	import { editMode, itemHeight, motion } from '$lib/Stores';
	import { openModal } from 'svelte-modals';

	export let sel: any;

	/**
	 * Handle click
	 */
	async function handleClick() {
		if ($editMode) {
			openModal(() => import('$lib/Modal/EmptyConfig.svelte'), { sel });
		}
	}
</script>

<!-- svelte-ignore a11y-click-events-have-key-events -->
<!-- svelte-ignore a11y-no-static-element-interactions -->
<div
	on:click={handleClick}
	class="container"
	style:height="{$itemHeight}px"
	style:opacity={$editMode ? '1' : '0'}
	style:transition="opacity {$motion}ms ease"
/>

<style>
	.container {
		width: 14.5rem;
		background-color: rgba(255, 255, 255, 0.25);
		border-radius: 0.65rem;
		margin: 0;
		outline: 2px dashed #fff;
		outline-offset: -2px;
	}

	/* Phone and Tablet (portrait) */
	@media all and (max-width: 768px) {
		.container {
			width: calc(50vw - 1.45rem);
		}
	}
</style>

```

2024-02-01 04:53 UTC, matt8707 commented on src/lib/Modal/EmptyConfig.svelte
> +</style>
```suggestion
<script lang="ts">
	import { lang } from '$lib/Stores';
	import type { EmptyItem } from '$lib/Types';
	import Modal from '$lib/Modal/Index.svelte';
	import ConfigButtons from '$lib/Modal/ConfigButtons.svelte';
	import Empty from '$lib/Main/Empty.svelte';

	export let isOpen: boolean;
	export let sel: EmptyItem;
</script>

{#if isOpen}
	<Modal>
		<h1 slot="title">{$lang('empty')}</h1>
		<h2>{$lang('preview')}</h2>

		<div>
			<Empty {sel} />
		</div>

		<ConfigButtons {sel} />
	</Modal>
{/if}

<style>
	div {
		pointer-events: none;
	}
</style>

```

2024-02-01 09:11 UTC, xrolfex commented
Requested changes applied.

2024-02-01 09:15 UTC, matt8707 approved these changes

2024-02-01 09:15 UTC, merged